### ISSUE TITLE
Clipping Bug Update

### ISSUE THREAD

**Issue by xdemoted** [gecolay/GSit#208]
Apologies if it isn't warranted to create a new issue, I wasn't sure if you get notified on things that have already been closed.

To isolate this issue entirely, I have created a server running one plugin exclusively, that being GSit. The bug was able to be consistently replicated by typing in the /sit command, holding shift, and then pressing enter. This instantly ejects the player and they phase through the block below them.

Config was not modified at all.

[Video](https://cdn.discordapp.com/attachments/1205575997471326258/1341638468526149642/Minecraft__1.21.3_-_Multiplayer_3rd-party_Server_2025-02-18_23-09-07.mp4?ex=67b6b9b1&is=67b56831&hm=efaf5cf6e5e6672f6b2773c9d6b128be52ccac6bab54240663204976009c1008&)

![Image](https://github.com/user-attachments/assets/f24d9798-f5f8-40e8-a4a6-7ea70785ea6c)

![Image](https://github.com/user-attachments/assets/8e5a7848-1c4f-442e-9bb3-b37686373800)

![Image](https://github.com/user-attachments/assets/f07ac44b-eec8-40b2-82ce-3059b56878c1)

Quick Addition: The vanilla sitting behavior can also replicate this by doing something similar with boats.

**Comment by gecolay** [comment]
@xdemoted Can you reproduce this issue on a 1.17.x server?

**Comment by xdemoted** [comment]
> [@xdemoted](https://github.com/xdemoted) Can you reproduce this issue on a 1.17.x server?

From what I can tell, on 1.17, the issue is worse, consistently clipping through whatever block you are sitting on when getting up.

[Video](https://files.catbox.moe/qgppgp.mp4)

Same version of GSit.

**Comment by afoxxvi** [comment]
Can also confirm in Paper 1.21.1, with GSit 2.2.0, players can pass through the block below them by standing on a carpet block, keep hitting right-click and shift quickly.

**Comment by StKillReal** [comment]
The same issue with latest purpur 1.21.4 and latest version of the plugin

**Comment by Stonley890** [comment]
Also using Purpur 1.21.4. Players can clip through full blocks as well as slabs and stairs on top of full blocks.

Video: https://nextcloud.macver.org/s/sCjjQsaAaEy3Ggy

**Comment by gecolay** [comment]
@Stonley890 @StKillReal @afoxxvi @xdemoted @adaptableRuben Please try to reproduce the issue with this test version of GSit:
https://github.com/gecolay/GSit/releases/download/2.2.1/GSit-2.2.0.jar

**Comment by Stonley890** [comment]
I was not able to reproduce the issue on this version.

**Comment by afoxxvi** [comment]
Can still reproduce, like in the video
https://drive.google.com/file/d/1i5RvDZxK-um4smqXf4ha79nk8JAFgZ1M/view?usp=drive_link

**Comment by Stonley890** [comment]
@afoxxvi that video is private.

**Comment by gecolay** [comment]
This bug should be fixed by update 2.2.1, please try it out. https://github.com/gecolay/GSit/releases/tag/2.2.1

**Comment by afoxxvi** [comment]
@Stonley890 @gecolay 
Sorry for this late mention and the video should be available now.
And I can still reproduce this issue in v2.2.1, same behavior has the video above.
